// Vamanan GPT knowledge base.
// Each entry: { id, title, tags, body, source, followups }

export const KNOWLEDGE = [
  {
    id: "what",
    title: "What is Vamanan?",
    tags: ["what is vamanan", "who is vamanan", "vamanan", "about vamanan", "introduction", "intro", "what", "who"],
    body: "Vamanan is the dwarf incarnation of Lord Vishnu, the fifth of the ten Dashavatara avatars. He appeared during the reign of the benevolent asura king Mahabali to restore the cosmic balance that the king's growing pride had disturbed. Vamanan appears small, almost overlooked — a short brahmachari (celibate student) carrying a wooden umbrella and a kamandalu (water pot). Yet within that humble form burns the full power of Vishnu, the preserver of the universe. The story of Vamanan is the story of how the smallest gesture can hold the largest meaning: how a dwarf's request for three paces of land became the moment the infinite revealed itself through the finite.",
    source: "Bhagavata Purana, Skanda 8",
    followups: ["What is the story of Vamanan and Mahabali?", "What do the three steps mean?", "How is Vamanan connected to Onam?"],
  },
  {
    id: "story",
    title: "The Story of Vamanan and Mahabali",
    tags: ["story", "mahabali", "vamanan story", "three steps", "three worlds", "legend", "tale", "narrative", "myth", "vamanan and mahabali", "vamanan mahabali"],
    body: "King Mahabali ruled the three worlds with such generosity and justice that even the gods grew uneasy. His subjects adored him; there was no lie, no poverty, no fear under his reign. But his fame and power had grown so vast that Indra, king of the gods, felt his own throne tremble. The gods appealed to Lord Vishnu for help.\n\nVishnu was born as Vamanan — a dwarf brahmachari, no taller than a young boy. He arrived at the great yajna (sacrifice) where Bali was granting boons to all who came. The small sage asked for just three paces of land, measured by his own tiny feet. Bali's guru, Shukracharya, recognized the dwarf as Vishnu himself and warned the king not to grant the request. But Bali had given his word — and a king who breaks his promise is no king at all.\n\nThe moment Bali poured the ceremonial water granting the boon, Vamanan began to grow. He expanded into Trivikrama, the cosmic giant. With his first stride he covered the entire earth. With his second, he reached the heavens and the space beyond. For the third stride, there was nowhere left to step. Bali, understanding at last, knelt and offered his own head. Vamanan placed his foot upon it and sent the king to Sutala, the netherworld — not as punishment, but as honor. Bali was beloved forever, and granted the boon of returning to his people once a year: that return is Onam.",
    source: "Bhagavata Purana 8.15–22",
    followups: ["What do the three steps mean?", "Who was King Mahabali?", "How is Vamanan connected to Onam?"],
  },
  {
    id: "meaning",
    title: "What the Three Steps Mean",
    tags: ["meaning", "symbolism", "three steps meaning", "interpretation", "what does it mean", "significance", "deeper meaning", "philosophy", "three steps"],
    body: "The three steps of Vamanan are among the most layered symbols in Hindu mythology. They operate on multiple levels simultaneously:\n\nOn the cosmic level: the first stride covers the earth (Bhumi), the second covers the heavens (Dyauh), and the third has nowhere to go but the self — Bali's own head. The three steps encompass all of measurable reality and then step beyond it.\n\nOn the philosophical level: the first step represents all that you can see and own — the material world. The second represents all that you can imagine and desire — the world of aspiration and dream. When both are given away, the only thing left is the self. Bali's offering of his head is the surrender of ego — and in that surrender, the self is not destroyed but preserved eternally.\n\nOn the ethical level: the story teaches that true generosity has no limit and no self-protection. Bali knew he would lose everything, yet he kept his word. The three steps are a test of whether your dharma (duty) can survive your own loss.\n\nVamanan's message: the infinite arrives only after the finite has been fully surrendered.",
    source: "Interpretive tradition",
    followups: ["What is the story of Vamanan and Mahabali?", "Why does Vamanan still matter today?", "What is Trivikrama?"],
  },
  {
    id: "onam",
    title: "Vamanan and Onam",
    tags: ["onam", "festival", "kerala", "mahabali return", "celebration", "ponnonam", "flower carpet", "athappookkalam", "onam festival", "what is onam"],
    body: "Onam is the state festival of Kerala, celebrated over ten days (Atham to Thiruvonam) during the Malayalam month of Chingam (August–September). At its heart is the promise of Vamanan: because Bali gave himself willingly and kept his word even unto loss, Vamanan granted him a boon — once a year, King Mahabali may return to his beloved people to see them happy and prosperous.\n\nOnam is that return. Every element of the celebration is a welcome:\n\n• Pookkalam: intricate flower carpets (also called Athappookkalam) laid daily before homes, growing in size each day, welcoming the king with beauty.\n\n• Sadya: a grand vegetarian feast served on banana leaves, featuring 20–30 dishes including avial, sambar, payasam, and parippu curry — a meal of abundance fit for a king.\n\n• Vallamkali: snake boat races on the backwaters, especially at Aranmula and Punnamada, with long chundan boats rowed by dozens of men.\n\n• Kaikottikali and Thumbi Thullal: traditional group dances performed by women in Mundu and Kasavu sarees around the pookkalam.\n\n• Pulikali: performers painted as tigers and leopards dance through the streets of Thrissur.\n\n• Onathappan: clay or wooden figures of Mahabali and Vamanan placed beside the pookkalam.\n\nVamanan is the silent presence behind every Onam — the one who made the return possible.",
    source: "Kerala oral tradition",
    followups: ["What are the essential dishes in an Onam Sadya?", "How to make a Pookkalam?", "Who was King Mahabali?"],
  },
  {
    id: "vishnu",
    title: "Vamanan as an Avatar of Vishnu",
    tags: ["vishnu", "avatar", "dashavatara", "incarnation", "god", "divine", "fifth avatar", "trivikrama", "ten avatars"],
    body: "Vamanan is the fifth avatar of the Dashavatara — the ten incarnations of Lord Vishnu, each appearing at a moment of cosmic crisis to restore dharma. The ten avatars are: Matsya (fish), Kurma (turtle), Varaha (boar), Narasimha (man-lion), Vamana (dwarf), Parashurama, Rama, Krishna, Buddha (or Balarama, depending on tradition), and Kalki.\n\nVamanan is unique among them because he conquers without a weapon, without an army, without anger. His only instrument is a request, and his only force is truth. Where other avatars wield swords, bows, or chakras, Vamanan wields a request for three paces of land. In his dwarf form he is Vamanan; in his cosmic, all-spanning form he is Trivikrama, 'the one who took three steps.'\n\nThe avatar teaches that divine power does not always arrive with thunder — sometimes it comes as a small figure at the door, asking for almost nothing. The power is not in the size of the form but in the truth of the purpose.",
    source: "Dashavatara tradition",
    followups: ["What is the story of Vamanan and Mahabali?", "What is Trivikrama?", "What are the ten avatars of Vishnu?"],
  },
  {
    id: "mahabali",
    title: "Who Was King Mahabali?",
    tags: ["mahabali", "king bali", "bali", "asura king", "generous king", "who is mahabali", "maveli", "king mahabali"],
    body: "Mahabali — known affectionately as Maveli in Kerala — was an asura (demon) king, but unlike the common image of asuras, he was just, generous, and beloved by all his subjects. Under his rule there was no lie, no poverty, no fear. His kingdom was described as a golden age where dharma stood on four legs.\n\nHe was the grandson of Prahlada, the great devotee of Vishnu, and the son of Virochana. Despite being born into the asura lineage, Bali's virtue was so great that it threatened the gods — not because he was cruel, but because he was loved. His fame spread across the three worlds, and his power grew until even Indra's throne seemed insecure.\n\nVamanan's test was not a punishment for evil — it was a reckoning with a goodness that had grown too proud of itself. Bali's grace is that he kept his word even when he knew he would lose everything. When Vamanan asked for three paces of land, Bali's guru Shukracharya warned him, but the king refused to withdraw his promise. In losing his kingdom, Bali became eternal — granted the boon of returning once a year to his people, which is celebrated as Onam.\n\nIn Kerala, Mahabali is not a villain. He is the beloved king, the generous father, the one who gave everything and was honored for it. The song 'Maveli Naadu Vaneedum Kalam' describes his reign as a time when all people were equal and none suffered.",
    source: "Bhagavata Purana 8.14–15",
    followups: ["What is the story of Vamanan and Mahabali?", "How is Vamanan connected to Onam?", "What was Shukracharya's warning?"],
  },
  {
    id: "trivikrama",
    title: "Trivikrama — The Cosmic Form",
    tags: ["trivikrama", "cosmic form", "giant form", "three stepper", "vamanan giant", "universal form", "virat", "trivikrama form"],
    body: "The moment Bali granted the boon, Vamanan revealed his true nature: Trivikrama, the universe-spanning form. With one step he covered the earth; with the second he measured the heavens. The oceans trembled, the stars scattered, Brahma washed his feet with water from his kamandalu (which became the river Ganga), and every being saw that the small sage at the gate was the sustainer of all worlds.\n\nTrivikrama means 'the one who took three steps' — tri (three) + vikrama (stride). In Vedic tradition, this connects to the three steps of Vishnu mentioned in the Rigveda, where Vishnu's three strides encompass the earth, the atmosphere, and the heavens. The Vamanan avatar is the mythological embodiment of this ancient Vedic concept.\n\nTrivikrama is the moment the infinite shows itself through the finite — a reminder that scale is not a measure of significance, and that the smallest vessel can hold the whole cosmos. In temple iconography, Trivikrama is depicted with one leg lifted high (covering the heavens) and the other planted on the earth, with Bali kneeling beneath, offering his head.",
    source: "Bhagavata Purana 8.20",
    followups: ["What is the story of Vamanan and Mahabali?", "What do the three steps mean?", "Vamanan as an avatar of Vishnu"],
  },
  {
    id: "shukra",
    title: "Shukracharya's Warning",
    tags: ["shukracharya", "shukra", "guru", "warning", "advisor", "sage warning", "teacher", "bali guru"],
    body: "Shukracharya, guru of the asuras and one of the wisest sages in the tradition, saw through Vamanan's disguise instantly. He recognized the small dwarf as Vishnu himself, come to take everything Bali had. He pulled Bali aside and warned him: 'This is no ordinary brahmachari — this is the Preserver in disguise. Withdraw your promise, or you will lose all.'\n\nBut Bali refused. His reasoning was profound: 'A king who has given his word cannot take it back — not even to save his kingdom. My promise is my dharma.' When Shukracharya persisted, Bali declared that he would rather lose his kingdom than his honor.\n\nShukracharya, in his frustration, is said to have shrunk himself to enter the spout of the water vessel to block the flow of water — but Vamanan, seeing this, pushed a blade of darbha grass into the spout, blinding one of Shukracharya's eyes. (This is why Shukracharya is sometimes depicted with one eye.)\n\nShukracharya's warning is the voice of self-preservation; Bali's answer is the voice of dharma. The story honors both: the guru for seeing the truth, and the king for choosing it.",
    source: "Bhagavata Purana 8.19",
    followups: ["What is the story of Vamanan and Mahabali?", "Who was King Mahabali?", "What do the three steps mean?"],
  },
  {
    id: "relevance",
    title: "Why Vamanan Still Matters Today",
    tags: ["relevance", "today", "modern", "why", "lesson", "teaching", "moral", "learn", "values", "apply", "why does it matter", "still matter"],
    body: "Vamanan's story is not locked in scripture — it is a mirror held up to every generation. Here is why it still matters:\n\n1. The danger of unchecked pride: Bali was not evil — he was good, and his goodness became his blind spot. Power that is generous but cannot see its own limit is the most dangerous kind. Every era has its Mahabali.\n\n2. The power of keeping your word: In a world of broken promises and strategic dishonesty, Bali's refusal to withdraw his word — even knowing it would cost him everything — is a radical ethical statement. Your word is your dharma.\n\n3. True generosity has no self-protection: Bali gave knowing he would lose. That is the highest form of generosity — not giving from surplus, but giving from the knowledge that giving will cost you.\n\n4. The small can hold the infinite: Vamanan appeared as the least. In a world obsessed with scale, followers, and visibility, the story says: the small step, taken in truth, can cover the world. Do not judge by appearance.\n\n5. Loss can be transformation, not defeat: Bali did not lose — he was preserved. Sometimes what looks like losing everything is the moment you become eternal.\n\nThe teaching is simple and hard: keep your word, honor what you give, and understand that true greatness is measured not by how much you hold but by what you are willing to offer.",
    source: "Reflective tradition",
    followups: ["What do the three steps mean?", "What is the story of Vamanan and Mahabali?", "Who was King Mahabali?"],
  },
  {
    id: "name",
    title: "The Name 'Vamanan'",
    tags: ["name", "meaning of name", "vamanan meaning", "etymology", "word", "sanskrit", "dwarf", "what does vamanan mean"],
    body: "Vamanan comes from the Sanskrit 'Vamana' (वामन), meaning 'dwarf' or 'the small one.' It is related to the root 'vam,' which can mean 'to send forth' or 'to measure out.' The name is one of deliberate humility — the infinite choosing to be called the least.\n\nIn Kerala, the name is pronounced 'Vamanan' with the Malayalam suffix. The name itself is the first teaching: do not judge by appearance, and do not assume that power must be large to be real. To say 'Vamanan' is to remember that the divine can stand at your door, the size of a child, and ask for almost nothing.\n\nThe name also carries the paradox at the heart of the avatar: the one called 'the small one' is the one who covers the universe in three steps. The name is the disguise and the revelation at once.",
    source: "Sanskrit etymological tradition",
    followups: ["What is Vamanan?", "Vamanan as an avatar of Vishnu", "What is Trivikrama?"],
  },
  {
    id: "temples",
    title: "Where Vamanan Is Worshipped",
    tags: ["temple", "temples", "worship", "where", "shrine", "thrikkakara", "vamanamurthy", "vamanan temple", "thrikkakara temple"],
    body: "The most ancient and significant shrine to Vamanan is the Thrikkakara Temple in Kochi, Kerala — believed to be the very spot where Vamanan received Mahabali's offering. The temple is the spiritual center of Onam celebrations across Kerala. The name 'Thrikkakara' itself is derived from 'Trik-kakara,' meaning 'the place of the three steps.'\n\nAt Thrikkakara, the idol shows Vamanan in his dwarf form, holding the umbrella and water pot of a brahmachari — small, serene, and quietly infinite. The temple's festival, Thrikkakara Vamanamoorthy Temple Festival, coincides with Onam and draws thousands.\n\nVamanan is also venerated across India as Trivikrama, particularly in temples like the Ulagalanda Perumal Temple in Kanchipuram (Tamil Nadu), where the deity stands 35 feet tall with one leg raised to the heavens. The Trivikrama form is also worshipped in the Thirukkurungudi Temple and several other Divya Desams (sacred Vishnu temples praised by the Alvars).\n\nIn the Dashavatara traditions, Vamanan is invoked as the avatar who teaches that the measure of divinity is not size but truth.",
    source: "Temple tradition, Kerala",
    followups: ["What is Vamanan?", "How is Vamanan connected to Onam?", "Vamanan as an avatar of Vishnu"],
  },
  {
    id: "sadya",
    title: "The Onam Sadya",
    tags: ["sadya", "feast", "food", "onam feast", "onam sadya", "dishes", "banana leaf", "meal", "parippu", "payasam", "avial", "sambar"],
    body: "The Onam Sadya is a grand vegetarian feast served on a banana leaf, the crown jewel of Onam celebrations. It typically features 20–30 dishes, and the arrangement on the leaf follows a precise tradition. Here are the essential components:\n\n• Parippu Curry: Moong dal with ghee, the first item served — the simplest and most sacred.\n\n• Sambar: Lentil stew with vegetables and tamarind, poured over rice.\n\n• Avial: A medley of vegetables (drumstick, yam, plantain, beans) cooked with coconut and curd.\n\n• Thoran: Vegetables stir-fried with grated coconut and turmeric — cabbage thoran, bean thoran, or carrot thoran.\n\n• Olan: White pumpkin and cowpeas cooked in coconut milk.\n\n• Kootu Curry: Yam and raw banana cooked with chickpeas and coconut.\n\n• Erissery: Pumpkin or yam cooked with coconut and spices.\n\n• Pachadi: Vegetables in a yogurt-coconut base, sometimes with a sweet note.\n\n• Kichadi: Vegetables in a spiced yogurt sauce (not to be confused with North Indian khichdi).\n\n• Pickles (Achar): Lime, mango, and lemon pickles for the sharp note.\n\n• Payasam: The grand finale — sweet pudding. Parippu payasam (moong dal), Ada payasam (rice flakes), or Pazham payasam (banana).\n\n• Banana chips, pappadam, and fresh banana complete the meal.\n\nThe sadya is eaten with the hands, seated on the floor, and served from the narrow end of the banana leaf. It is a meal of abundance — a king's welcome for a king who is returning home.",
    source: "Kerala culinary tradition",
    followups: ["How is Vamanan connected to Onam?", "How to make a Pookkalam?", "Who was King Mahabali?"],
  },
  {
    id: "pookkalam",
    title: "How to Make a Pookkalam",
    tags: ["pookkalam", "flower carpet", "athappookkalam", "how to make pookkalam", "flowers", "onam flowers", "athapoo"],
    body: "A Pookkalam (also called Athappookkalam) is a circular floral arrangement made on the ground to welcome King Mahabali during Onam. Here is how it is traditionally made:\n\n1. The Base: Clean the ground in front of the house. Draw a concentric circle pattern — traditionally ten rings for the ten days of Onam (Atham to Thiruvonam).\n\n2. The Flowers: Use fresh, brightly colored flowers — marigold (jamanthi), chrysanthemum, thumba (small white flowers), chembarathi (hibiscus), and mandaram. The flowers are plucked and arranged by hand, petal by petal.\n\n3. The Layers: Start from the outer ring and work inward. Each ring uses a different color. The outermost ring is usually orange or yellow marigold, then alternating white thumba, red chembarathi, and yellow chrysanthemum, with a central dot of bright color.\n\n4. The Daily Growth: On Atham (day 1), the pookkalam is small — just one ring. Each day a new ring is added. By Thiruvonam (day 10), it is a large, intricate mandala of ten concentric rings.\n\n5. The Onathappan: A small clay figure of Mahabali (and sometimes Vamanan) is placed in the center.\n\nThe pookkalam is more than decoration — it is a daily meditation, an offering of beauty to the returning king, and a communal activity that brings families together each morning of Onam.",
    source: "Kerala tradition",
    followups: ["How is Vamanan connected to Onam?", "What are the essential dishes in an Onam Sadya?", "Who was King Mahabali?"],
  },
  {
    id: "onappattu",
    title: "Onappattu — Onam Songs",
    tags: ["onappattu", "onam song", "song", "lyrics", "malayalam song", "onam music", "sing", "onam lyrics"],
    body: "Onappattu (Onam songs) are an essential part of Onam celebrations, sung during pookkalam arrangements, kaikottikali dances, and family gatherings. Here is a traditional Onam song in Malayalam:\n\nഓണം വന്നു ഓണായിട്ട്\nഓണം കിളിക്കാവിൽ പൂത്ത്\nമാവേലി നാട് വാണീടും കാലം\nമനുഷ്യർ സുഖമുള്ള കാലം\n\n(Onam vannu onnaayittu\nOnam kilikkaavil poothu\nMaaveli naadu vaaneedum kaalam\nManushyar sukhamulla kaalam)\n\nTranslation: 'Onam has come, Onam has bloomed in the kilikkaavu tree. The time when Maveli ruled the land — the time when all people were happy.'\n\nThe most famous Onam song is 'Maveli Naadu Vaneedum Kalam,' which describes Mahabali's golden reign:\n\nമാവേലി നാട് വാണീടും കാലം\nമനുഷ്യർ സുഖമുള്ള കാലം\nആടും കലകളും ആടിയാടി\nപാടും പാട്ടുകൾ പാടിപ്പാടി\n\nTranslation: 'When Maveli ruled the land, the people were happy. Dances and arts performed freely, songs were sung endlessly.'\n\nThese songs are not just music — they are oral history, keeping the memory of a beloved king alive across generations.",
    source: "Kerala folk tradition",
    followups: ["How is Vamanan connected to Onam?", "Who was King Mahabali?", "Tell me a Malayalam joke"],
  },
  {
    id: "dashavatara",
    title: "The Ten Avatars of Vishnu",
    tags: ["dashavatara", "ten avatars", "avatars of vishnu", "matsya", "kurma", "varaha", "narasimha", "kalki", "rama", "krishna"],
    body: "The Dashavatara are the ten primary incarnations of Lord Vishnu, each appearing to restore cosmic order (dharma) when it is threatened. They are, in order:\n\n1. Matsya (Fish) — Saved the first man, Manu, from a great deluge.\n\n2. Kurma (Turtle) — Supported Mount Mandara during the churning of the ocean of milk.\n\n3. Varaha (Boar) — Lifted the earth from the cosmic waters when the demon Hiranyaksha hid it.\n\n4. Narasimha (Man-Lion) — Destroyed the demon Hiranyakashipu to protect his devotee Prahlada.\n\n5. Vamana (Dwarf) — The avatar this GPT is about! Restored cosmic balance by humbling Mahabali's pride.\n\n6. Parashurama (Rama with an axe) — A warrior sage who cleared the earth of corrupt kings 21 times.\n\n7. Rama — The prince of Ayodhya, hero of the Ramayana.\n\n8. Krishna — The divine cowherd, charioteer of the Bhagavad Gita, and one of the most beloved deities.\n\n9. Buddha (or Balarama, depending on tradition) — The enlightened one.\n\n10. Kalki — The future avatar, who will appear at the end of the current age (Kali Yuga) to restore dharma.\n\nVamanan sits in the middle of this sequence — the pivot point — and is the only avatar who conquers through a request rather than force.",
    source: "Dashavatara tradition",
    followups: ["Vamanan as an avatar of Vishnu", "What is the story of Vamanan and Mahabali?", "What is Trivikrama?"],
  },
  {
    id: "greet",
    title: "Greetings!",
    tags: ["hi", "hello", "hey", "greetings", "namaste", "namaskaram", "good morning", "good evening", "yo", "sup", "halo", "hai", "onashamsakal"],
    body: "Namaskaram! Onashamsakal! I am Vamanan GPT — a keeper of Kerala's oldest stories and a companion for curious minds. Ask me about Vamanan, Mahabali, the three steps, Onam traditions, the Sadya feast, or anything at all. I answer with what the tradition holds, what it asks of us now, and a little bit of mischief when the mood is right. What would you like to know?",
    source: "Vamanan GPT",
    followups: ["What is Vamanan?", "Tell me the story of Vamanan and Mahabali", "Tell me a Malayalam joke"],
  },
  {
    id: "thanks",
    title: "You're Welcome",
    tags: ["thank you", "thanks", "thank", "nanni", "grateful", "appreciate"],
    body: "Nanni! It is my joy to share these stories. The beauty of a story is that it grows each time it is told — so thank you for asking, and for keeping the tradition alive. Is there anything else you would like to know?",
    source: "Vamanan GPT",
    followups: ["What is the story of Vamanan and Mahabali?", "How is Vamanan connected to Onam?", "Tell me a Malayalam joke"],
  },
  {
    id: "joke",
    title: "A Malayalam Joke",
    tags: ["joke", "funny", "malayalam joke", "chali", "comedy", "laugh", "humor", "jokes", "chodyam", "kadi"],
    body: "Here is a classic Kerala-style joke:\n\nTeacher: \"Nee enthu kettu padikkunnu?\" (What are you studying by listening?)\nStudent: \"Sir, headphones kettu padikkunnu.\" (Sir, I study by listening with headphones.)\n\nAnd another:\n\nAppachan: \"Mone, njan maranjapol enthu venam?\" (Son, what should be done when I die?)\nMone: \"Appachan, maranjittal etho onnum venam ennu parayenda. Onnam ullekkalum njan nokkam.\" (Father, no need to say anything when you die. As long as you're alive, I'll take care.)\n\nAnd one more for Onam:\n\nOnathinnaashtam vanna Maveli: \"Ente naatil ellarkum sughramanu, oru vishavum illa!\"\nKurangu: \"Athengil, ningalude IT cell eduthu nokkuvo?\" (Then, have you checked your IT cell?)\n\nVamanan GPT believes laughter is also a form of devotion. The gods laugh too — especially at our jokes.",
    source: "Kerala humor tradition",
    followups: ["Tell me another Malayalam joke", "How is Vamanan connected to Onam?", "What is the story of Vamanan and Mahabali?"],
  },
  {
    id: "vallamkali",
    title: "Vallamkali — The Snake Boat Races",
    tags: ["vallamkali", "boat race", "snake boat", "aranmula", "punnamada", "chundan", "boat", "race", "vallam"],
    body: "Vallamkali, the snake boat race, is one of the most thrilling spectacles of Onam. Long, slender boats called chundan vallam (snake boats) — some over 100 feet long and carrying 100+ rowers — race across Kerala's backwaters to the rhythm of vanchipattu (boat songs).\n\nThe most famous races:\n\n• Nehru Trophy Boat Race: Held on Punnamada Lake in Alappuzha, named after Jawaharlal Nehru who was so impressed by a race during his visit in 1952 that he donated a silver trophy.\n\n• Aranmula Uthrattathi Vallamkali: Held at Aranmula on the Uthrattathi star day, a more ritualistic and temple-connected race.\n\n• Champakulam Moolam Boat Race: One of the oldest, held on the Moolam star day.\n\nThe boats themselves are works of art — carved from jackfruit or aanjili wood, shaped like a hooded cobra, and painted with vibrant colors. The rowers row in perfect unison, singing vanchipattu — rhythmic folk songs that tell stories of kings and gods. A single mistimed stroke can capsize the entire boat.\n\nVallamkali is not just a race — it is a celebration of community, discipline, and the joy of Kerala's waters.",
    source: "Kerala tradition",
    followups: ["How is Vamanan connected to Onam?", "What are the essential dishes in an Onam Sadya?", "How to make a Pookkalam?"],
  },
  {
    id: "pulikali",
    title: "Pulikali — The Tiger Dance",
    tags: ["pulikali", "tiger dance", "pulikali", "kaduvakali", "thrissur", "folk dance", "onam dance"],
    body: "Pulikali (literally 'tiger play') is a recreational folk art performed during Onam, most famously in Thrissur. Performers paint their bodies as tigers and leopards — bright yellow, orange, and black stripes — and dance through the streets to the beat of percussion instruments like chenda and thakil.\n\nThe art form dates back over 200 years, when Maharaja Rama Varma Sakthan Thampuran introduced it as a way to celebrate Onam with wild, joyful energy. The body painting itself takes hours — artists use tempera colors to create elaborate tiger faces, stripes, and even whiskers on the performers' bodies.\n\nThe dancers perform playful scenes: a tiger 'hunting' a hunter, tigers pouncing, and mock fights between tigers. The crowd follows, cheering and laughing. It is one of the most photographed and beloved events of Onam — a moment where the whole city becomes a jungle of color and laughter.\n\nPulikali captures the spirit of Onam: joyful, communal, slightly chaotic, and utterly alive.",
    source: "Kerala folk tradition",
    followups: ["How is Vamanan connected to Onam?", "What is Vallamkali?", "How to make a Pookkalam?"],
  },
  {
    id: "kaikottikali",
    title: "Kaikottikali — The Clapping Dance",
    tags: ["kaikottikali", "kaikottikali", "thiruvathira", "dance", "women dance", "onam dance", "clapping dance"],
    body: "Kaikottikali (also spelled Thiruvathirakali) is a traditional group dance performed by women during Onam. Dancers — typically 8–20 women — form a circle around a lit nilavilakku (traditional brass oil lamp) and the pookkalam, moving in synchronized patterns while clapping their hands in rhythm.\n\nThe women wear traditional attire: Mundu and Kasavu (Kerala sarees with golden borders), fresh jasmine flowers in their hair, and traditional jewelry. The movements are graceful — circular, flowing, with rhythmic clapping and footwork.\n\nThe songs accompanying Kaikottikali are often devotional, praising deities like Shiva, Vishnu, and Krishna, or narrating stories from the epics. Some songs are playful, teasing, and celebratory — reflecting the joy of the season.\n\nKaikottikali is both a dance and a ritual: it honors the divine feminine, celebrates community among women, and keeps ancient rhythms alive. The lamp at the center — the nilavilakku — is the focal point, representing the light of tradition that is passed from one generation to the next.",
    source: "Kerala tradition",
    followups: ["How is Vamanan connected to Onam?", "What is Pulikali?", "How to make a Pookkalam?"],
  },
  {
    id: "nilavilakku",
    title: "Nilavilakku — The Sacred Lamp",
    tags: ["nilavilakku", "lamp", "oil lamp", "light", "vilakku", "brass lamp", "traditional lamp"],
    body: "The Nilavilakku is a traditional brass or bronze oil lamp used in Kerala homes and temples. 'Nila' means floor, and 'vilakku' means lamp — it is a lamp that stands on the floor. It has a wide base, a tall stem, and a shallow dish at the top where oil (usually coconut or sesame) is poured, with a cotton wick lit in the center.\n\nThe Nilavilakku is lit at dawn and dusk in traditional Kerala homes, and is central to every ceremony — births, weddings, festivals, and Onam. During Onam, it is placed at the center of the pookkalam, and women dance Kaikottikali around it.\n\nLighting the nilavilakku is not just functional — it is symbolic. The lamp represents knowledge dispelling ignorance, the divine presence in the home, and the continuity of tradition. The flame is never blown out — it is allowed to burn down naturally, or is used to light another lamp, passing the light forward.\n\nIn the context of Vamanan's story, the nilavilakku is the light that welcomes the returning king — a small, steady flame that says: 'We are here. We remember. Come home.'",
    source: "Kerala tradition",
    followups: ["How is Vamanan connected to Onam?", "What is Kaikottikali?", "How to make a Pookkalam?"],
  },
  {
    id: "kasavu",
    title: "Kasavu — The Golden Border",
    tags: ["kasavu", "mundu", "saree", "kerala saree", "golden border", "dress", "clothing", "traditional wear"],
    body: "Kasavu refers to the distinctive golden zari border on Kerala's traditional clothing — the Mundu (for men) and the Kerala Saree (for women). The cloth itself is white or off-white cotton, with a broad golden border (the kasavu) running along one edge. The contrast of pure white and gold is the visual signature of Kerala.\n\nDuring Onam, people wear new Kasavu clothing — it is considered auspicious to wear fresh, new clothes (called 'Onakkodi') for the festival. The golden border catches the light of the nilavilakku and the Onam sun, making the entire celebration shimmer.\n\nThe kasavu border is traditionally woven from real gold or gold-coated thread (zari), though modern versions use synthetic gold thread. The width of the border can vary — from a thin line to a broad band — and wider borders are considered more formal.\n\nKasavu is more than clothing — it is the visual identity of Kerala. When you see the white-and-gold, you see Kerala. When you see it during Onam, you see a people welcoming their king.",
    source: "Kerala textile tradition",
    followups: ["How is Vamanan connected to Onam?", "What is Kaikottikali?", "What is the Onam Sadya?"],
  },
  {
    id: "maveli_song",
    title: "Maveli Naadu Vaneedum Kalam",
    tags: ["maveli naadu", "maveli song", "maveli nadu vaneedum kalam", "song about mahabali", "onam song lyrics"],
    body: "'Maveli Naadu Vaneedum Kalam' is the most beloved Onam song in Kerala, describing the golden age of King Mahabali's reign. The lyrics, in Malayalam, paint a picture of a utopian society:\n\nമാവേലി നാട് വാണീടും കാലം\nമനുഷ്യർ സുഖമുള്ള കാലം\nആടും കലകളും ആടിയാടി\nപാടും പാട്ടുകൾ പാടിപ്പാടി\n\nകള്ളവുമില്ലാ നല്ലവരല്ലാ\nമനുഷ്യർ സുഖമുള്ള കാലം\nഒരു തീയതിയും ഭേദമില്ലാ\nഎല്ലാവരും സുഖമുള്ള കാലം\n\nTranslation: 'When Maveli ruled the land, the people were happy. Dances and arts performed freely, songs were sung endlessly. There were no liars, no bad people — all were happy. No distinction of caste or class — everyone was equal and joyful.'\n\nThe song is a vision of an ideal society — and Onam is the annual remembering of that vision. It is not nostalgia for a past that existed, but a longing for a future that could. Every time the song is sung, it asks: what would it take for this to be true again?",
    source: "Kerala folk tradition",
    followups: ["Who was King Mahabali?", "How is Vamanan connected to Onam?", "Tell me an Onam song"],
  },
  {
    id: "thrikkakara",
    title: "Thrikkakara — The Sacred Origin",
    tags: ["thrikkakara", "origin of onam", "onam origin", "where onam started", "thrikkakara temple", "vamanamoorthy"],
    body: "Thrikkakara, a village in present-day Kochi (Ernakulam district), is considered the mythological origin of Onam. The Thrikkakara Temple, dedicated to Vamanamoorthy (Vamanan), is believed to be the exact spot where King Mahabali conducted his great yajna and where Vamanan appeared to receive his offering.\n\nThe name 'Thrikkakara' is derived from 'Trik-kakara,' meaning 'the place of the three steps' — a direct reference to Vamanan's three cosmic strides. The temple is one of the 108 Divya Desams (sacred Vishnu temples praised by the Alvar saints).\n\nDuring Onam, Thrikkakara becomes the spiritual epicenter of Kerala's celebrations. The temple festival runs concurrently with Onam, and the Onam celebrations of the Kochi royal family are traditionally centered here. The temple grounds host cultural performances, and the idol of Vamanamoorthy is taken in procession.\n\nThrikkakara is to Onam what Bethlehem is to Christmas — the place where the story began, and the place where it is remembered most deeply.",
    source: "Temple tradition, Kerala",
    followups: ["Where is Vamanan worshipped?", "What is the story of Vamanan and Mahabali?", "How is Vamanan connected to Onam?"],
  },
];

// General knowledge entries — for off-topic questions
export const GENERAL_KNOWLEDGE = {
  // Technology
  "ai artificial intelligence machine learning": {
    title: "On Artificial Intelligence",
    body: "Artificial intelligence is the field of building systems that can perceive, reason, and act — loosely modeled on human cognition. Modern AI is largely powered by machine learning, where statistical models find patterns in data and use them to make predictions. The current wave — large language models like the one you're talking to — works by predicting the next most likely token in a sequence, trained on vast text corpora. It is powerful, but it is not consciousness. It is pattern, not understanding. The interesting question is not 'can machines think' but 'what does thinking even mean, and who gets to define it?'",
    source: "Vamanan GPT — reflecting on its own nature",
  },
  "programming code software developer coding": {
    title: "On Programming",
    body: "Programming is the art of giving precise instructions to a machine. At its best, it is a form of engineering and a form of poetry simultaneously — you are building structures out of pure logic, and those structures can do anything from running a spaceship to displaying a joke. The key insight every programmer eventually reaches: the code is not for the computer, it is for the next human who has to read it. Write clearly, name things well, and the machine will follow.",
    source: "Vamanan GPT — a philosophical aside",
  },
  "space universe cosmos astronomy planets stars": {
    title: "On the Cosmos",
    body: "The universe is approximately 13.8 billion years old, and it contains at least 200 billion galaxies, each with hundreds of billions of stars. We are on a small rocky planet orbiting an average star in an outer arm of the Milky Way. The most humbling fact in all of science is this: every atom in your body heavier than hydrogen was forged in the core of a star and scattered across space when that star died. You are, quite literally, stardust contemplating stardust. Vamanan would appreciate the symmetry — the infinite within the finite, the cosmos within the small.",
    source: "Vamanan GPT — looking up",
  },
  "mathematics math numbers calculation equation": {
    title: "On Mathematics",
    body: "Mathematics is the language of pattern, structure, and relationship. It is the only field where truth is absolute — once a theorem is proven, it is true forever, in every possible universe. The beauty of math is that it starts with the simplest questions (what is a number? what does it mean to count?) and arrives at the most abstract (infinity, topology, the nature of space itself). It is the closest thing we have to a universal language — one that would work on any planet, in any galaxy, for any mind capable of reason.",
    source: "Vamanan GPT — counting the steps",
  },
  "history historical past ancient civilization": {
    title: "On History",
    body: "History is not the past — it is the story we tell about the past, and the story changes depending on who is telling it. The study of history is the practice of learning to hold multiple, contradictory narratives at once and still find meaning. The ancient civilizations — Mesopotamia, Egypt, the Indus Valley, Greece, Rome, the Mayans — all grappled with the same questions we do: how to live together, how to govern, what happens after death, what the gods want. We are not smarter than they were. We just have better tools and more data.",
    source: "Vamanan GPT — keeper of old stories",
  },
  "philosophy meaning of life existence reality": {
    title: "On Philosophy",
    body: "Philosophy is the practice of asking the questions that cannot be answered with certainty, and then refusing to stop asking. The big three — What exists? What can we know? How should we live? — have been asked for 2,500 years and are no closer to resolution. That is not a failure; it is the point. The value is in the asking. As Socrates put it: 'The unexamined life is not worth living.' Vamanan's story is, in its own way, a philosophical text: it asks what it means to give, what it means to lose, and what it means to be small in a world that worships size.",
    source: "Vamanan GPT — thinking aloud",
  },
  "music song instrument art creative": {
    title: "On Music and Art",
    body: "Music is the most direct of the arts — it bypasses language and speaks to something pre-verbal in us. A melody can make you cry in a language you don't speak. Art, in all its forms, is the human attempt to say the thing that cannot quite be said — to capture a feeling, a moment, a truth that is too slippery for ordinary words. The best art does not explain; it reveals. It says: 'Look. Listen. Feel. This is what it is to be alive.'",
    source: "Vamanan GPT — listening",
  },
  "food cooking recipe eat cuisine dish": {
    title: "On Food",
    body: "Food is culture made edible. Every cuisine tells the story of a place — its climate, its trade routes, its history, its values. Kerala's food, for instance, is shaped by its coastlines (coconut, fish), its spice trade (black pepper, cardamom, cloves — once the most valuable commodities in the world), and its community of Syrian Christians, Muslims, and Hindus who each contributed dishes. The Onam Sadya — 20+ dishes on a banana leaf — is a miniature encyclopedia of Kerala on a plate. To eat well is to understand a place.",
    source: "Vamanan GPT — at the table",
  },
  "science biology physics chemistry nature": {
    title: "On Science",
    body: "Science is not a body of knowledge — it is a method. It is the practice of forming a hypothesis, testing it against reality, and being willing to be wrong. The most powerful sentence in science is 'I don't know, but let's find out.' Science has given us medicine, electricity, spaceflight, and the understanding that we are made of stardust on a wet rock orbiting a ball of fire. It is the most successful tool humanity has ever invented for figuring out what is actually true.",
    source: "Vamanan GPT — observing",
  },
  "health exercise fitness body wellness": {
    title: "On Health",
    body: "Your body is the only home you will ever truly own. Treat it accordingly. The basics are unglamorous and well-known: move your body regularly, eat mostly plants, sleep enough, drink water, manage stress, and maintain social connections. There is no shortcut, no hack, no supplement that replaces these. The good news is that the basics work. The hard part is that the basics require consistency, not intensity. Small steps, taken every day — Vamanan would approve.",
    source: "Vamanan GPT — on the body",
  },
  "love relationship marriage family": {
    title: "On Love and Relationships",
    body: "Love is the practice of seeing another person clearly — their flaws, their fears, their beauty — and choosing to stay. It is not a feeling; feelings come and go. It is a commitment, renewed daily. The relationships that last are not the ones without conflict but the ones where both people keep choosing each other after the conflict. Mahabali's story is, at its core, about love too — the love of a king for his people, so deep that he returns every year to see them happy.",
    source: "Vamanan GPT — on the heart",
  },
  "business money work career job": {
    title: "On Work and Purpose",
    body: "The question is not 'what job should I do' but 'what kind of life do I want to have?' Work is a means, not an end. The most fulfilled people are not the ones with the most prestigious titles but the ones whose daily work aligns with their values. If you can find work that is useful to others, interesting to you, and sustainable for your body and mind, you have found something rare. Everything else is noise.",
    source: "Vamanan GPT — on vocation",
  },
  "travel journey explore world trip": {
    title: "On Travel",
    body: "Travel is the practice of making the unfamiliar familiar. The best travel is not about ticking off landmarks but about the moments in between — a conversation with a stranger, a meal you didn't expect, a street that smells different from any street you know. Kerala itself is one of the world's great destinations: the backwaters, the tea gardens of Munnar, the spice markets, the beaches. If you ever visit during Onam, you will see a place that knows how to celebrate.",
    source: "Vamanan GPT — on the road",
  },
  "football soccer sport game cricket": {
    title: "On Sports",
    body: "Sport is organized play — a structured space where humans test the limits of body, mind, and teamwork. It matters because play matters. The joy of watching a great athlete is the joy of seeing a human being do something almost impossible, and making it look natural. Whether it is cricket in India, football across the world, or the snake boat races of Kerala — sport is a shared language that needs no translation.",
    source: "Vamanan GPT — on play",
  },
  "book read literature story novel": {
    title: "On Books and Reading",
    body: "Reading is the cheapest, most accessible form of time travel. For the price of a book, you can sit with the greatest minds in history, visit any century, live any life. The habit of reading is the single most reliable predictor of lifelong curiosity and empathy. If you read widely — fiction, nonfiction, poetry, history — you will never be bored, and you will never be fully alone. You will always have a conversation partner.",
    source: "Vamanan GPT — on the page",
  },
  "weather rain climate season monsoon": {
    title: "On Weather and Seasons",
    body: "Kerala has two monsoons — the Southwest (Edavappathy, June–September) and the Northeast (Thulavarsham, October–November). The monsoon is not just rain; it is the rhythm of life in Kerala. It fills the rivers, green the rice fields, and sets the calendar for festivals. Onam itself falls at the end of the monsoon, when the land is green and full — the harvest celebration is a thank-you to the rain. Without the monsoon, there is no Onam, no sadya, no pookkalam. The rain is the first gift.",
    source: "Vamanan GPT — on the rain",
  },
  "kerala god's own country backwater": {
    title: "On Kerala",
    body: "Kerala — 'God's Own Country' as the tourism slogan says — is a narrow strip of land between the Western Ghats and the Arabian Sea on India's southwest coast. It is one of the most densely populated regions on earth, yet it has the highest literacy rate in India, the highest life expectancy, and a unique culture shaped by centuries of spice trade with the world. The backwaters — a network of canals, rivers, and lakes — are Kerala's signature landscape. The tea gardens of Munnar, the beaches of Kovalam, the wildlife of Thekkady, and the temples of Thrissur make it one of the most diverse small places on earth. And Onam is its heartbeat.",
    source: "Vamanan GPT — on home",
  },
  "language malayalam sanskrit hindi english": {
    title: "On Language",
    body: "Malayalam is the language of Kerala — one of the 22 scheduled languages of India, with over 35 million speakers. It belongs to the Dravidian language family and shares roots with Tamil, though it has been heavily influenced by Sanskrit over centuries. The script is derived from the Grantha script, which itself evolved from Brahmi. Malayalam has one of the richest literary traditions in India, with poetry dating back over a thousand years. The word 'Malayalam' itself is interesting — it is a palindrome in its script (മലയാളം), and it means 'hill-land' (mala = hill, alam = land).",
    source: "Vamanan GPT — on words",
  },
  "diwali holi festival india hindu": {
    title: "On Indian Festivals",
    body: "India has more festivals than there are days in the year. Each region, each community, each tradition has its own. Diwali (the festival of lights, celebrating the return of Rama to Ayodhya), Holi (the festival of colors, celebrating spring and the burning of Holika), Navratri (nine nights of dance and devotion to the Goddess), Eid (celebrated by India's 200 million Muslims), Christmas (especially in Kerala, which has a large Christian community), and Onam — each festival is a window into a different facet of Indian civilization. Onam is unique because it is not just a Hindu festival; it is a cultural festival of Kerala, celebrated by Hindus, Christians, and Muslims alike. It belongs to everyone.",
    source: "Vamanan GPT — on celebration",
  },
};

// Additional Malayalam jokes
export const MALAYALAM_JOKES = [
  {
    title: "School Days",
    body: "Teacher: \"Ente mole, enthu kondu njan late aayi?\"\nStudent: \"Sir, board-il 'School' ennu ezhuthiyirunnu, athu kondu njan slow aayi varunnathu.\" (Sir, the board said 'School,' so I came slowly.)\n\nTeacher: \"But that doesn't make sense!\"\nStudent: \"Sir, 'Slow' is in 'School' — athu kondu.\" (Sir, 'Slow' is in 'School' — that's why.)",
  },
  {
    title: "Onam Special",
    body: "Onam-inaashappettu Maveli IT-office-leku vannu.\nManager: \"Maveli, nee enthu kondu IT-leku?\"\nMaveli: \"Onam aanallo, njan work-from-home cheyyunnathu.\" (It's Onam, I'm working from home.)\nManager: \"Pakshe ithu office aanallo!\"\nMaveli: \"Athengil, njan office-leku aanallo work cheyyunnathu — balance!\" (Then I work from the office — balance!)",
  },
  {
    title: "Kerala Traffic",
    body: "Auto driver: \"Sir, meter-il 40 rupees aanu, pakshe njan 60 edukkam ennu parayunnundu.\"\nPassenger: \"Ente? Meter-pporu 40, pakshe 60?\"\nAuto driver: \"Sir, meter-pporu 40, rest-pporu 20 — comfort charge!\" (Sir, 40 for the meter, 20 for the rest — comfort charge!)\n\nPassenger: \"Athengil comfort-pporu enthu?\"\nAuto driver: \"Sir, njan poovally poovally ennu drive cheyyunnathu — athu comfort-pporu!\" (Sir, I drive without any pothole issues — that's the comfort!)",
  },
  {
    title: "Appam and Coffee",
    body: "Waiter: \"Sir, enthu venam?\"\nCustomer: \"Oru appavum oru coffee-um.\"\nWaiter: \"Appam matram aanu, coffee aayi.\"\nCustomer: \"Appam matram? Pakshe coffee-um veno!\"\nWaiter: \"Sir, appam-pporu coffee-um veno? Appam matram aanu, coffee-um varum.\" (Sir, only appam? Coffee will come.)\n\nCustomer: \"Athengil, appam-pporu coffee-um veno?\"\nWaiter: \"Sir, njan parayunnundu — appam matram aanu, coffee aayi!\" (Sir, I said — only appam, coffee is coming!)\n\n(This joke loses something in translation, which is itself the joke.)",
  },
  {
    title: "The Philosophical Kochiite",
    body: "Friend 1: \"Ninte life-le aim enthu?\" (What is the aim of your life?)\nFriend 2: \"Onnu njan ariyilla.\" (I don't know one thing.)\nFriend 1: \"Ariyillengil, enthu cheyyum?\" (If you don't know, what will you do?)\nFriend 2: \"Ariyillathathu kondu, njan ariyunnathu cheyyum.\" (Because I don't know, I'll do what I know.)\nFriend 1: \"Ariyunnathu enthu?\" (What do you know?)\nFriend 2: \"Onnu njan ariyilla.\" (I don't know one thing.)\n\n(And so it goes, in the tradition of Kerala's circular conversations.)",
  },
];

export const STARTERS = [
  { label: "What is Vamanan?", query: "What is Vamanan?", emoji: "🪔" },
  { label: "The legend of Mahabali & Vamanan", query: "Tell me the story of Vamanan and Mahabali", emoji: "👑" },
  { label: "What do the three steps mean?", query: "What do the three steps mean?", emoji: "👣" },
  { label: "Onam Sadya dishes", query: "What are the essential dishes in an Onam Sadya?", emoji: "🍛" },
  { label: "Write me an Onam song", query: "Write me an Onappattu in Malayalam", emoji: "🎶" },
  { label: "Tell me a Malayalam joke", query: "Tell me a Malayalam joke", emoji: "😄" },
  { label: "How to make a Pookkalam?", query: "How to make a Pookkalam?", emoji: "🌼" },
  { label: "Why does Vamanan matter today?", query: "Why does Vamanan still matter today?", emoji: "✨" },
];
